package com.eonoohx.mituxtlaapp.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF066B5B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA0F2DE)
val onPrimaryContainerLight = Color(0xFF005144)
val secondaryLight = Color(0xFF8C4A5F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E1)
val onSecondaryContainerLight = Color(0xFF703347)
val tertiaryLight = Color(0xFF436278)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC8E6FF)
val onTertiaryContainerLight = Color(0xFF2B4A5F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF7)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FBF7)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFDBE5E0)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7976)
val outlineVariantLight = Color(0xFFBFC9C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3230)
val inverseOnSurfaceLight = Color(0xFFECF2EF)
val inversePrimaryLight = Color(0xFF84D6C2)
val surfaceDimLight = Color(0xFFD5DBD8)
val surfaceBrightLight = Color(0xFFF5FBF7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F1)
val surfaceContainerLight = Color(0xFFE9EFEC)
val surfaceContainerHighLight = Color(0xFFE3EAE6)
val surfaceContainerHighestLight = Color(0xFFDEE4E0)